language: node_js
node_js:
  - lts/*

branches:
only:
  - master

cache: npm

install:
  - npm ci

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm audit --production
        - npm run test
    - stage: build
      script:
        - npm run build

stages:
  - lint
  - test
  - build